# Generated by Django 4.1.1 on 2022-10-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zayavky.car_mark')),
            ],
        ),
        migrations.CreateModel(
            name='Car_engin_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zayavky.car_model')),
            ],
        ),
    ]
